[Feature]
LogPoller = true

[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[Database]
MaxIdleConns = 20 
MaxOpenConns = 200 

[[EVM]]
ChainID = '31337'
Enabled = true
MinIncomingConfirmations = 1 
FinalityDepth = 1 
LogPollInterval = '1s' 
LinkContractAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3'

[[EVM.Nodes]]
Name = 'Hardhat'
HTTPURL = 'http://host.docker.internal:8545'
WSURL = 'ws://host.docker.internal:8545'

[EVM.Transactions]
MaxInFlight = 2000
MaxQueued = 5000 
ReaperInterval = '10s' 
ResendAfterThreshold = '1m' 

[EVM.GasEstimator]
Mode = 'FixedPrice'
BumpThreshold = 0
PriceDefault = '1 gwei'

[EVM.GasEstimator.BlockHistory]
BlockHistorySize = 0

[JobPipeline]
MaxSuccessfulRuns = 50

[Telemetry]
Enabled = false